# -*- coding: utf-8 -*-
"""Copy of day3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UbxI-xIJwjihgsvO1tNytTaNVOKio4_3
"""

lst = ['akash', 'doulat', 'ramesh', 'daniyal']
type(lst)
lst[0]
lst[2]

lst = ['peacock', 'paroat', 'monkey',['jeevat', 'munesh','pawan']]
lst[3][1]

lst = ['peacock', 'paroat', 'monkey',['jeevat', 'munesh','pawan']]
lst[-1][-1]

#dictionary

dit = {"name": "sandeep", "age":28, "email":"sudeepsuther@gmail.com"}
dit
dit["name"]

#@title Default title text
#set
Covid1stDose= ["43567", "43267", "43567","86475"]
Covid1stDose
len(Covid1stDose)

#set
Covid1stDose= ["43567", "43267", "43567","86475"]
Covid1stDose
len(Covid1stDose)
len(set(Covid1stDose))

lst(0)

